
version: "3"

services:
  frontend:
    container_name: "frontend"
    build: frontend
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"

  backend:
    container_name: "backend"
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - network

networks:
  network:
    driver: bridge
